language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t pgolpys/docker-react -f Docerfile.dev .

script:
  - docker run pgolpys/docker-react npm run test -- --coverage
